apiVersion: v1	
kind: Service	
metadata:	
  name: employee-backend
  labels:
    app: employee-backend
spec:	
  ports:	
  - port: 80	
    targetPort: 8080
    name: http
  selector:	
    app: employee-backend
  type: ClusterIP
